name: deploy-test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build Next.js app
        run: |
          npm install
          npm start

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          server: ${{ secrets.HOST  }}
          username: ${{ secrets.USERNAME  }}
          key: ${{ secrets.KEY  }}
          source: .
          target: /home/ubuntu/test/frontend

      - name: Restart PM2 process on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: pm2 restart myapp